clients:
  demo@client.com:
    display_name: "Demo Grower"
    drive_folder_id: ""
    units:
      temperature: "C"
      vpd: "kPa"
      par: "µmol·m⁻²·s⁻¹"
    setpoints:
      air_temp_day: 24.0
      air_temp_night: 20.0
      vpd_target: 0.8
